name: Deploy Node.js App to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip project
      run: zip -r build.zip . -x ".git/*" "node_modules/*" "*.pem"

    - name: Decode SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Copy files to EC2
      run: |
        scp -i ec2_key.pem -o StrictHostKeyChecking=no build.zip ec2-user@51.21.132.194:/home/ec2-user/

    - name: SSH and deploy
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@51.21.132.194 << 'EOF'
          unzip -o build.zip -d app
          cd app
          npm install
          pm2 restart all || pm2 start index.js --name course-institute
        EOF
